In [4]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [5]:
dataFile = "iris.csv"
print(dataFile)

iris.csv


In [6]:
df = pd.read_csv(dataFile)
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [8]:
print(X[0:5])
print(y[0:5])

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [9]:
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [10]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [11]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [12]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [14]:
print(X_train[0:5])

[[5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.5 0.3]]


In [15]:
print(y_train[0:5])

[[ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]]


In [16]:
print(X_test[0:5])

[[6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.  2.  3.5 1. ]
 [5.5 2.4 3.7 1. ]
 [4.4 2.9 1.4 0.2]]


In [17]:
print(y_test[0:5])

[[False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]]


In [24]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='sigmoid')
  ])
model

In [25]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [26]:
with tf.device('/gpu:0'):
	model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 5ms/step - loss: 2.1758 - accuracy: 0.3529
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 1.9383 - accuracy: 0.3529
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 1.7837 - accuracy: 0.3529
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 1.6568 - accuracy: 0.3529
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 1.5569 - accuracy: 0.3529
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 1.4654 - accuracy: 0.3529
Epoch 7/100
3/3 [==============================] - 0s 5ms/step - loss: 1.3964 - accuracy: 0.3529
Epoch 8/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3489 - accuracy: 0.3529
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 1.3073 - accuracy: 0.3529
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 1.2697 - accuracy: 0.3529
Epoch 11/100
3/3 [===========

In [27]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.43670424818992615
Test accuracy: 1.0


In [28]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 38ms/step


array([[0.04381043, 0.3996038 , 0.50200427],
       [0.03956152, 0.4141643 , 0.46915364],
       [0.13365373, 0.49046975, 0.38511094],
       [0.13018572, 0.50232947, 0.3724209 ],
       [0.87083834, 0.40988076, 0.4503499 ],
       [0.01631912, 0.33153227, 0.5246127 ],
       [0.03064852, 0.38888627, 0.4594049 ],
       [0.10246772, 0.4880054 , 0.41399416],
       [0.05023609, 0.3995086 , 0.46573985],
       [0.0856595 , 0.48236638, 0.4355288 ],
       [0.87096864, 0.39487785, 0.4337592 ],
       [0.8450002 , 0.4045666 , 0.41464695],
       [0.08288918, 0.46733204, 0.43559298],
       [0.84345937, 0.4002219 , 0.4098098 ],
       [0.88986415, 0.40276432, 0.4669516 ],
       [0.05111613, 0.42506355, 0.45589548],
       [0.02920999, 0.3795869 , 0.4867727 ],
       [0.0811825 , 0.4788123 , 0.3793761 ],
       [0.90381795, 0.3775548 , 0.4554348 ],
       [0.93829316, 0.36361355, 0.50464916],
       [0.69047403, 0.4385837 , 0.35724357],
       [0.88895184, 0.38822252, 0.45172212],
       [0.

In [29]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
Predicted: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]


Teniendo una modificación pequeña, solamente modificando solamente las funciones de activación de 'sigmoid' a 'relu' de las primeras 2 capas de 10 neuronas cada una y la utilización de la GPU para el entrenamiento del modelo, se obtuvo ya un accuracy con los datos de testing de 100%, por esto, no se modifico algo adicional.